# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=__MINECRAFT_VERSION__
loader_version=__LOADER_VERSION__
# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=__MAVEN_GROUP__
archives_base_name=__ARCHIVES_NAME__
# Dependencies
# check this on https://modmuss50.me/fabric.html
__FABRIC_API_PROPERTY__
loom_version=__LOOM_VERSION__
__YARN_PROPERTY__
kotlin_loader_version=__KOTLIN_LOADER_VERSION__
